"""PAE Registry — deterministic first-class resource registry for this repository.

The registry is generated by ``scripts/generate_registry.py``. This package holds
the pieces that generator composes:

``membership``    approved roots, anchored exclusions, kind detection
``identity``      UID + public-ID derivation and the frozen identity ledger
``adapters``      per-kind normalization of native source formats
``relationships`` reorg (move / supersede / merge / split) and vendored copy edges
``governance``    maturity, review, evaluation, provenance, license, serving policy
``schema``        a standard-library JSON Schema subset validator
``build``         assembles records and emits the generated artifacts

Everything here is standard library plus PyYAML, per ADR-0003.
"""

REGISTRY_RECORD_SCHEMA_VERSION = "pae-registry-record/1"
