"""Consumer-side registry validation.

Deliberately not a second copy of ``scripts/generate_registry.py --check``.
That check is the *producer's*: it re-derives corpus membership, kinds, UIDs
and relationships and proves the committed registry is what the generator
would emit. This one is the *consumer's*: it takes the registry as given and
asks whether the assumptions the Engine makes when serving from it actually
hold in this checkout.

The split matters because the two run in different places. A consumer may hold
a checkout the generator never ran in — a shallow clone, an export, a vendored
copy, a registry regenerated by a newer producer. It needs to know the registry
is safe to trust without owning the machinery that produced it.

What this never does: discover the corpus, classify kinds, derive UIDs, verify
the identity freeze, apply overrides, migrate ledgers, parse techniques, or
regenerate anything.
"""

from __future__ import annotations

import hashlib
import json
import stat as stat_module
from collections import Counter
from dataclasses import dataclass
from typing import Any, Iterable, Mapping, Optional

from .errors import IncompatibleRegistry, RegistryValidationError
from .models import RECORD_SCHEMA, Record, Summary
from .registry import PUBLIC_ID_PATTERN, UID_PATTERN, Registry, _validate_relative_path
from .repository import Repository

__all__ = ["Issue", "ValidationReport", "validate_registry", "recount", "summary_drift"]

_REQUIRED_FIELDS = (
    "schema_version",
    "uid",
    "kind",
    "id",
    "aliases",
    "lifecycle",
    "title",
    "serving_policy",
)

#: Relationship fields holding bare UIDs, and those holding typed edges.
_UID_LIST_FIELDS = ("copies", "supersedes", "merges")
_UID_SCALAR_FIELDS = ("copy_of",)
_EDGE_SCALAR_FIELDS = ("superseded_by", "merged_into")
_EDGE_LIST_FIELDS = ("split_into",)


@dataclass(frozen=True)
class Issue:
    code: str
    message: str
    severity: str = "error"
    details: Mapping[str, Any] | None = None

    def to_json_obj(self) -> dict[str, Any]:
        obj: dict[str, Any] = {
            "code": self.code,
            "severity": self.severity,
            "message": self.message,
        }
        if self.details:
            obj["details"] = dict(self.details)
        return obj


@dataclass(frozen=True)
class ValidationReport:
    ok: bool
    issues: tuple[Issue, ...]
    checked: Mapping[str, Any]
    checksums_verified: bool

    def to_json_obj(self) -> dict[str, Any]:
        return {
            "ok": self.ok,
            "issue_count": len(self.issues),
            "issues": [i.to_json_obj() for i in self.issues],
            "checked": dict(self.checked),
            "checksums_verified": self.checksums_verified,
        }


def recount(records: Iterable[Record]) -> dict[str, Any]:
    """Recount the summary's load-bearing tallies straight from the records.

    Serving policy is counted from the *declared* value rather than the
    engine's fail-closed interpretation, so a drift report compares like with
    like against what the generator wrote.
    """
    total = 0
    lifecycle: Counter[str] = Counter()
    kinds: Counter[str] = Counter()
    kinds_live: Counter[str] = Counter()
    kinds_tombstone: Counter[str] = Counter()
    policies: Counter[str] = Counter()
    for record in records:
        total += 1
        lifecycle[record.lifecycle] += 1
        kinds[record.kind] += 1
        if record.lifecycle == "live":
            kinds_live[record.kind] += 1
        elif record.lifecycle == "tombstone":
            kinds_tombstone[record.kind] += 1
        policies[str(record.serving_policy_declared)] += 1
    return {
        "total_records": total,
        "by_lifecycle": dict(lifecycle),
        "by_kind": dict(kinds),
        "by_kind_live": dict(kinds_live),
        "by_kind_tombstone": dict(kinds_tombstone),
        "by_serving_policy": dict(policies),
    }


def summary_drift(summary: Summary, counts: Mapping[str, Any]) -> list[dict[str, Any]]:
    """Every tally where the summary and the records disagree."""
    declared = {
        "total_records": summary.total_records,
        "by_lifecycle": dict(summary.by_lifecycle),
        "by_kind": dict(summary.by_kind),
        "by_kind_live": dict(summary.by_kind_live),
        "by_kind_tombstone": dict(summary.by_kind_tombstone),
        "by_serving_policy": dict(summary.by_serving_policy),
    }
    drift = []
    for field_name, expected in declared.items():
        actual = counts[field_name]
        if expected != actual:
            drift.append({"field": field_name, "summary": expected, "records": actual})
    return drift


def validate_registry(
    repository: Repository, *, verify_checksums: bool = False
) -> ValidationReport:
    """Check the consumer trust assumptions, collecting every failure.

    Collecting rather than stopping at the first failure is the point: an agent
    told about one broken record will fix it and re-run, four times. The one
    thing that does stop the run is an unsupported record schema, because
    beyond that boundary the Engine cannot even name the fields it is checking.
    """
    issues: list[Issue] = []
    root = repository.root
    registry_path = repository.registry_path

    uids: set[str] = set()
    public_ids: set[str] = set()
    alias_owner: dict[str, str] = {}
    pending_edges: list[tuple[str, str, str]] = []
    records: list[Record] = []

    line_count = 0
    with open(registry_path, "r", encoding="utf-8") as fh:
        for lineno, line in enumerate(fh, 1):
            if not line.strip():
                continue
            line_count += 1
            try:
                obj = json.loads(line)
            except json.JSONDecodeError as exc:
                issues.append(
                    Issue(
                        "malformed_json_line",
                        f"line {lineno} is not valid JSON: {exc}",
                        details={"line": lineno},
                    )
                )
                continue
            if not isinstance(obj, dict):
                issues.append(
                    Issue(
                        "record_not_object",
                        f"line {lineno} is not a JSON object",
                        details={"line": lineno},
                    )
                )
                continue

            declared_schema = obj.get("schema_version")
            if declared_schema != RECORD_SCHEMA:
                # A contract violation, not a data-quality finding. Continuing
                # would mean validating fields whose meaning is unknown.
                raise IncompatibleRegistry(
                    f"{registry_path}:{lineno} declares record schema {declared_schema!r}, "
                    f"which this engine does not implement (supported: {RECORD_SCHEMA!r})",
                    path=str(registry_path),
                    line=lineno,
                    declared_schema=declared_schema,
                    supported_schema=RECORD_SCHEMA,
                )

            missing = [f for f in _REQUIRED_FIELDS if f not in obj]
            if missing:
                issues.append(
                    Issue(
                        "missing_required_field",
                        f"line {lineno} omits required field(s): {', '.join(missing)}",
                        details={"line": lineno, "uid": obj.get("uid"), "missing": missing},
                    )
                )
                continue

            record = Record.from_raw(obj)
            records.append(record)

            _check_identity(record, lineno, uids, public_ids, alias_owner, issues)
            _collect_edges(record, pending_edges)
            _check_source(record, root, issues, verify_checksums)

    _check_alias_shadowing(alias_owner, public_ids, issues)

    for owner_uid, field_name, ref in pending_edges:
        if ref not in uids:
            issues.append(
                Issue(
                    "dangling_relationship_uid",
                    f"{owner_uid}.relationships.{field_name} points at {ref!r}, which no "
                    "record claims",
                    details={"uid": owner_uid, "field": field_name, "ref": ref},
                )
            )

    # Summary consistency. An unsupported summary schema already failed at
    # discovery, so reaching here means the schema is one we implement.
    summary = Registry.open(repository).stats()
    drift = summary_drift(summary, recount(records))
    for entry in drift:
        issues.append(
            Issue(
                "summary_drift",
                f"summary {entry['field']} disagrees with the records",
                details=entry,
            )
        )

    checked = {
        "repository": str(root),
        "records": len(records),
        "lines": line_count,
        "unique_uids": len(uids),
        "unique_public_ids": len(public_ids),
        "aliases": len(alias_owner),
        "relationship_edges": len(pending_edges),
        "summary_schema": summary.schema,
    }
    return ValidationReport(
        ok=not issues,
        issues=tuple(issues),
        checked=checked,
        checksums_verified=verify_checksums,
    )


def _check_identity(
    record: Record,
    lineno: int,
    uids: set[str],
    public_ids: set[str],
    alias_owner: dict[str, str],
    issues: list[Issue],
) -> None:
    if not UID_PATTERN.match(record.uid):
        issues.append(
            Issue(
                "invalid_uid",
                f"line {lineno} carries a malformed UID: {record.uid!r}",
                details={"line": lineno, "uid": record.uid},
            )
        )
    elif record.uid in uids:
        issues.append(
            Issue(
                "duplicate_uid",
                f"UID {record.uid} appears more than once",
                details={"uid": record.uid, "line": lineno},
            )
        )
    else:
        uids.add(record.uid)

    if not PUBLIC_ID_PATTERN.match(record.id):
        issues.append(
            Issue(
                "invalid_public_id",
                f"{record.uid} carries a malformed public ID: {record.id!r}",
                details={"uid": record.uid, "id": record.id},
            )
        )
    elif record.id in public_ids:
        issues.append(
            Issue(
                "duplicate_public_id",
                f"public ID {record.id} appears more than once",
                details={"id": record.id, "uid": record.uid},
            )
        )
    else:
        public_ids.add(record.id)

    for alias in record.aliases:
        if not PUBLIC_ID_PATTERN.match(alias):
            issues.append(
                Issue(
                    "invalid_alias",
                    f"{record.uid} carries a malformed alias: {alias!r}",
                    details={"uid": record.uid, "alias": alias},
                )
            )
            continue
        if alias in alias_owner:
            issues.append(
                Issue(
                    "duplicate_alias",
                    f"alias {alias} is claimed by both {alias_owner[alias]} and {record.uid}",
                    details={"alias": alias, "uids": [alias_owner[alias], record.uid]},
                )
            )
            continue
        alias_owner[alias] = record.uid


def _check_alias_shadowing(
    alias_owner: Mapping[str, str], public_ids: set[str], issues: list[Issue]
) -> None:
    for alias, owner in sorted(alias_owner.items()):
        if alias in public_ids:
            issues.append(
                Issue(
                    "alias_shadows_public_id",
                    f"retired alias {alias} (held by {owner}) is also a live public ID; "
                    "a lookup would be ambiguous",
                    details={"alias": alias, "uid": owner},
                )
            )


def _collect_edges(record: Record, pending: list[tuple[str, str, str]]) -> None:
    relationships = record.raw.get("relationships") or {}
    for field_name in _UID_SCALAR_FIELDS:
        value = relationships.get(field_name)
        if isinstance(value, str):
            pending.append((record.uid, field_name, value))
    for field_name in _UID_LIST_FIELDS:
        for value in relationships.get(field_name) or ():
            if isinstance(value, str):
                pending.append((record.uid, field_name, value))
    for field_name in _EDGE_SCALAR_FIELDS:
        edge = relationships.get(field_name)
        ref = _resource_edge_ref(edge)
        if ref is not None:
            pending.append((record.uid, field_name, ref))
    for field_name in _EDGE_LIST_FIELDS:
        for edge in relationships.get(field_name) or ():
            ref = _resource_edge_ref(edge)
            if ref is not None:
                pending.append((record.uid, field_name, ref))


def _resource_edge_ref(edge: Any) -> Optional[str]:
    """A relationship edge's UID, but only when it points at a resource.

    Edges may also point at documents or collections, which are not registry
    records and must not be reported as dangling.
    """
    if isinstance(edge, Mapping) and edge.get("object_kind") == "resource":
        ref = edge.get("ref")
        return ref if isinstance(ref, str) else None
    return None


def _check_source(
    record: Record, root: Any, issues: list[Issue], verify_checksums: bool
) -> None:
    if record.lifecycle != "live" or not record.source_path:
        return

    rel = record.source_path
    reason = _validate_relative_path(rel)
    if reason is not None:
        issues.append(
            Issue(
                "unsafe_source_path",
                f"{record.id}: {reason} ({rel!r})",
                details={"uid": record.uid, "id": record.id, "path": rel, "reason": reason},
            )
        )
        return

    resolved = (root / rel).resolve()
    if not resolved.is_relative_to(root):
        issues.append(
            Issue(
                "source_path_escape",
                f"{record.id}: source path resolves outside the repository root",
                details={
                    "uid": record.uid,
                    "id": record.id,
                    "path": rel,
                    "resolved": str(resolved),
                },
            )
        )
        return

    try:
        st = resolved.stat()
    except FileNotFoundError:
        issues.append(
            Issue(
                "missing_source_file",
                f"{record.id}: source file does not exist ({rel})",
                details={"uid": record.uid, "id": record.id, "path": rel},
            )
        )
        return
    except OSError as exc:
        issues.append(
            Issue(
                "source_unreadable",
                f"{record.id}: source file could not be inspected ({rel}): {exc}",
                details={"uid": record.uid, "id": record.id, "path": rel},
            )
        )
        return

    if not stat_module.S_ISREG(st.st_mode):
        issues.append(
            Issue(
                "source_not_regular_file",
                f"{record.id}: source path is not a regular file ({rel})",
                details={"uid": record.uid, "id": record.id, "path": rel},
            )
        )
        return

    if not record.content_sha256 or record.checksum_payload != "raw_source_bytes":
        issues.append(
            Issue(
                "missing_checksum",
                f"{record.id}: live file-backed record carries no verifiable checksum, so "
                "its body can never be served",
                details={
                    "uid": record.uid,
                    "id": record.id,
                    "path": rel,
                    "content_sha256": record.content_sha256,
                    "checksum_payload": record.checksum_payload,
                },
            )
        )
        return

    if not verify_checksums:
        return

    try:
        data = resolved.read_bytes()
    except OSError as exc:
        issues.append(
            Issue(
                "source_unreadable",
                f"{record.id}: source file could not be read ({rel}): {exc}",
                details={"uid": record.uid, "id": record.id, "path": rel},
            )
        )
        return
    actual = "sha256:" + hashlib.sha256(data).hexdigest()
    if actual != record.content_sha256:
        issues.append(
            Issue(
                "checksum_mismatch",
                f"{record.id}: {rel} does not match its recorded checksum",
                details={
                    "uid": record.uid,
                    "id": record.id,
                    "path": rel,
                    "expected": record.content_sha256,
                    "actual": actual,
                },
            )
        )


def raise_if_invalid(report: ValidationReport) -> None:
    """Turn a failing report into the typed error the CLI maps to exit 9."""
    if not report.ok:
        raise RegistryValidationError(
            f"registry validation found {len(report.issues)} problem(s)",
            issue_count=len(report.issues),
            issues=[i.to_json_obj() for i in report.issues],
        )
